//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureTrustAgent.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecureTrustAgent.Localization.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon ICTK_logo_white_V {
            get {
                object obj = ResourceManager.GetObject("ICTK_logo_white_V", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   You can check product information and information related to technology.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SET_INFORM_SUBTITLE {
            get {
                return ResourceManager.GetString("SET_INFORM_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can set information related to the operation of the application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SET_SET_SUBTITLE {
            get {
                return ResourceManager.GetString("SET_SET_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program is already running. Please try again after closing the running program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_APP_STARTFAIL_MESSAGE {
            get {
                return ResourceManager.GetString("STR_APP_STARTFAIL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WARNING과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_APP_TITLE_WARNING {
            get {
                return ResourceManager.GetString("STR_APP_TITLE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_BTN_RUNADMINPAGE {
            get {
                return ResourceManager.GetString("STR_BTN_RUNADMINPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_BTN_SIGNIN {
            get {
                return ResourceManager.GetString("STR_BTN_SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The registration process has failed. Would you like to retry the operation? 
        ///Please reconnect the USB and select the &quot;Check&quot; button.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_FAIL_AND_RETRY_REG_MSG {
            get {
                return ResourceManager.GetString("STR_FAIL_AND_RETRY_REG_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_INFOM_MAINTITLE {
            get {
                return ResourceManager.GetString("STR_INFOM_MAINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is PUF?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_INFORM_FIRSTWHAT {
            get {
                return ResourceManager.GetString("STR_INFORM_FIRSTWHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is different?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_INFORM_SECONDWHAT {
            get {
                return ResourceManager.GetString("STR_INFORM_SECONDWHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What can you do?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_INFORM_THIRDWHAT {
            get {
                return ResourceManager.GetString("STR_INFORM_THIRDWHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MENU_EXIT {
            get {
                return ResourceManager.GetString("STR_MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MENU_INFO {
            get {
                return ResourceManager.GetString("STR_MENU_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OPEN과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MENU_OPEN {
            get {
                return ResourceManager.GetString("STR_MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MENU_SETTING {
            get {
                return ResourceManager.GetString("STR_MENU_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please place your finger overr the sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_AUTHHELPMESSAGE {
            get {
                return ResourceManager.GetString("STR_MFA_AUTHHELPMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please remove your finger and put it back again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_AUTHHELPSUBMESSAGE {
            get {
                return ResourceManager.GetString("STR_MFA_AUTHHELPSUBMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_CONTENT_CLOSE {
            get {
                return ResourceManager.GetString("STR_MFA_CONTENT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_CONTENT_RETRY {
            get {
                return ResourceManager.GetString("STR_MFA_CONTENT_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login operation failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAIL_RESULTMSG_FIRST {
            get {
                return ResourceManager.GetString("STR_MFA_FAIL_RESULTMSG_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clicking the Retry button restarts the authentication process.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAIL_RESULTMSG_SECOND {
            get {
                return ResourceManager.GetString("STR_MFA_FAIL_RESULTMSG_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We couldn&apos;t find the connected USB.
        ///Please check the USB connection status and try again.
        ///Would you like to try again?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAILANDFINMSG {
            get {
                return ResourceManager.GetString("STR_MFA_FAILANDFINMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mfa 인증작업이 실패 했습니다. 
        ///연결 중인 USB가 있다면 재 연결 후 작업을 다시 시도해 주세요.
        ///작업을 종료 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAILANDFINMSG_V2 {
            get {
                return ResourceManager.GetString("STR_MFA_FAILANDFINMSG_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연결중인 USB를 찾을 수 없습니다.
        ///USB 연결상태를 확인 후 다시 시도해 주세요.
        ///다시 시도 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAILANDRETRYMSG {
            get {
                return ResourceManager.GetString("STR_MFA_FAILANDRETRYMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The MFA authentication process has failed. 
        ///Would you like to retry the authentication process?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAILMSG {
            get {
                return ResourceManager.GetString("STR_MFA_FAILMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   authentication failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_FAILTITLE {
            get {
                return ResourceManager.GetString("STR_MFA_FAILTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initiating authentication process. Please tap your fingerprint on the device with blinking LED.
        ///If the LED turns red upon fingerprint contact, please try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_HELPMSG {
            get {
                return ResourceManager.GetString("STR_MFA_HELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The registration process has been completed.
        ///Please disconnect the connected USB device from your PC and reconnect it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_REGPUFHELPMSG {
            get {
                return ResourceManager.GetString("STR_MFA_REGPUFHELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will start the re-registration process. Please tap your fingerprint on the device with the blinking LED.
        ///Re-registration involves resetting the previous registration and proceeding with the registration process.
        ///After entering the previously registered fingerprint for authentication, once the authentication is complete, the reset and re-registration process will proceed.
        ///Please review the request message displayed on the screen and proceed with the task.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_REREGHELPMSG {
            get {
                return ResourceManager.GetString("STR_MFA_REREGHELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are conducting user verification for the cancellation process. If MFA authentication is successful, the cancellation process will proceed, and all existing registration information will be deleted after the completion of the process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_RESETHELPMSG {
            get {
                return ResourceManager.GetString("STR_MFA_RESETHELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The cancellation process has been completed.
        ///Please disconnect the connected USB device from your PC and reconnect it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_RESETRESULTHELPMSG {
            get {
                return ResourceManager.GetString("STR_MFA_RESETRESULTHELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration process initiated. Please tap your fingerprint on the device with flashing LED.
        ///We will collect your fingerprint three times for registration.
        ///Please check the message on the screen requesting recontact of the fingerprint and proceed with the registration process.
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_SIGNUPHELPMSG {
            get {
                return ResourceManager.GetString("STR_MFA_SIGNUPHELPMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login operation completed successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_SUCCESS_RESULTMSG_FIRST {
            get {
                return ResourceManager.GetString("STR_MFA_SUCCESS_RESULTMSG_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click the close button to call the admin page.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFA_SUCCESS_RESULTMSG_SECEND {
            get {
                return ResourceManager.GetString("STR_MFA_SUCCESS_RESULTMSG_SECEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MFAREG_FAILTITLE {
            get {
                return ResourceManager.GetString("STR_MFAREG_FAILTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to save your last login information? 
        ///This information will be utilized upon the restart of the PC Agent.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_MSG_SAVELASTLOGININFO {
            get {
                return ResourceManager.GetString("STR_MSG_SAVELASTLOGININFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SecureTrust과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("STR_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fingerprint authentication failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_RETSTR_FAIL_MFAAUTH {
            get {
                return ResourceManager.GetString("STR_RETSTR_FAIL_MFAAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fingerprint authentication was successful과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_RETSTR_SUCCESS_MFAAUTH {
            get {
                return ResourceManager.GetString("STR_RETSTR_SUCCESS_MFAAUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting up the security login feature for the admin page.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_CHANG_HTTPLISTENERHELP_V2 {
            get {
                return ResourceManager.GetString("STR_SET_CHANG_HTTPLISTENERHELP_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change language on your application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_CHANGELANGHELP {
            get {
                return ResourceManager.GetString("STR_SET_CHANGELANGHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * http Listen PORT :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_HTTP_LINTEN_PORT {
            get {
                return ResourceManager.GetString("STR_SET_HTTP_LINTEN_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_LANGUAGE {
            get {
                return ResourceManager.GetString("STR_SET_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to proceed with the change? 
        ///The program restarts on progress.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_LANGUAGE_WARNMSG {
            get {
                return ResourceManager.GetString("STR_SET_LANGUAGE_WARNMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you like to proceed with the change?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_LANGUAGE_WARNMSG2 {
            get {
                return ResourceManager.GetString("STR_SET_LANGUAGE_WARNMSG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_MAINTITLE {
            get {
                return ResourceManager.GetString("STR_SET_MAINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_SAVE {
            get {
                return ResourceManager.GetString("STR_SET_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * TCP Server Listen IP Address :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_SSH_SET_IPADDR {
            get {
                return ResourceManager.GetString("STR_SET_SSH_SET_IPADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * TCP Server Listen PORT :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_SSH_SET_PORT {
            get {
                return ResourceManager.GetString("STR_SET_SSH_SET_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings for SSH security login.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_SSHLOGINHELP {
            get {
                return ResourceManager.GetString("STR_SET_SSHLOGINHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * Web Listen IP Address :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_WEB_SET_IPADDR {
            get {
                return ResourceManager.GetString("STR_SET_WEB_SET_IPADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * Web Listen PORT :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_WEB_SET_PORT {
            get {
                return ResourceManager.GetString("STR_SET_WEB_SET_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings for web administrator security login.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SET_WEBADMINHELP {
            get {
                return ResourceManager.GetString("STR_SET_WEBADMINHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancellation completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SIGNOUT_TITLE {
            get {
                return ResourceManager.GetString("STR_SIGNOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will begin the USB registration cancellation process.
        ///Once the process starts, all previously registered information will be deleted.
        ///Would you like to proceed with the operation?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SIGNOUT_WARN_MSG {
            get {
                return ResourceManager.GetString("STR_SIGNOUT_WARN_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_SIGNUP_TITLE {
            get {
                return ResourceManager.GetString("STR_SIGNUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wating...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_WATING_DLGMSG {
            get {
                return ResourceManager.GetString("STR_WATING_DLGMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   re-Registration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_WINTITLE_MFA_REJOIN {
            get {
                return ResourceManager.GetString("STR_WINTITLE_MFA_REJOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign-In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_WINTITLE_MFA_SIGNIN {
            get {
                return ResourceManager.GetString("STR_WINTITLE_MFA_SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign-Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_WINTITLE_MFA_SIGNOUT {
            get {
                return ResourceManager.GetString("STR_WINTITLE_MFA_SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign-Up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_WINTITLE_MFA_SIGNUP {
            get {
                return ResourceManager.GetString("STR_WINTITLE_MFA_SIGNUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   task error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string STR_WORKERROR_TITLE {
            get {
                return ResourceManager.GetString("STR_WORKERROR_TITLE", resourceCulture);
            }
        }
    }
}
